name: Build and save my Docker image to a registry

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'   # Étape 5 → ne se déclenche que si backend change

env:
  REG_NAME: "acrinfofd21210.azurecr.io" # Nom du registy
  IMAGE_NAME: "backend-app-cco" # Nom de votre image


env:
  IMAGE_NAME: backend-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }} todo-app/src/backend
      # Push vers la registry
      - name: Push Docker image
        run: |
          docker push ${{ env.REG_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
